use_frameworks!

target 'wxxPresent_Example' do
  pod 'wxxPresent', :path => '../'

  target 'wxxPresent_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
